-- MySQL Script generated by MySQL Workbench
-- Sat Mar 23 14:25:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RareGen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RareGen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RareGen` DEFAULT CHARACTER SET utf8 ;
USE `RareGen` ;

-- -----------------------------------------------------
-- Table `RareGen`.`Patient_Association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Patient_Association` (
  `idPatient_Associations` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NULL,
  `Contact_telephone` VARCHAR(40) NULL,
  `Contact email` VARCHAR(45) NULL,
  `Description` LONGTEXT NULL,
  `Website` VARCHAR(200) NULL,
  PRIMARY KEY (`idPatient_Associations`),
  UNIQUE INDEX `idPatient_Associations_UNIQUE` (`idPatient_Associations` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease` (
  `idDiseases` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(500) NULL,
  `Orphacode` INT UNSIGNED NULL,
  `Description` LONGTEXT NULL,
  `Treatments` LONGTEXT NULL,
  PRIMARY KEY (`idDiseases`),
  INDEX `Orphacode` (`Orphacode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease_has_Patient_Association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease_has_Patient_Association` (
  `Diseases_idDiseases` INT UNSIGNED NOT NULL,
  `Patient_Associations_idPatient_Associations` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Diseases_idDiseases`, `Patient_Associations_idPatient_Associations`),
  INDEX `fk_Diseases_has_Patient Associations_Patient Associations1_idx` (`Patient_Associations_idPatient_Associations` ASC) VISIBLE,
  INDEX `fk_Diseases_has_Patient Associations_Diseases_idx` (`Diseases_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Diseases_has_Patient Associations_Diseases`
    FOREIGN KEY (`Diseases_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseases_has_Patient Associations_Patient Associations1`
    FOREIGN KEY (`Patient_Associations_idPatient_Associations`)
    REFERENCES `RareGen`.`Patient_Association` (`idPatient_Associations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Country` (
  `idCountry` INT NOT NULL,
  `Country_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Country_has_Patient_Association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Country_has_Patient_Association` (
  `Country_idCountry` INT NOT NULL,
  `Patient_Association_idPatient_Associations` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Country_idCountry`, `Patient_Association_idPatient_Associations`),
  INDEX `fk_Country_has_Patient Association_Patient Association1_idx` (`Patient_Association_idPatient_Associations` ASC) VISIBLE,
  INDEX `fk_Country_has_Patient Association_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Country_has_Patient Association_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `RareGen`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Country_has_Patient Association_Patient Association1`
    FOREIGN KEY (`Patient_Association_idPatient_Associations`)
    REFERENCES `RareGen`.`Patient_Association` (`idPatient_Associations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Gene` (
  `idGene` INT NOT NULL,
  `Name` VARCHAR(300) NULL,
  `Gene_type` VARCHAR(100) NULL,
  `Locus` VARCHAR(100) NULL,
  `Ensembl_id` VARCHAR(15) NULL,
  `OMIM_id` INT NULL,
  `GenAtlas_id` VARCHAR(20) NULL,
  `HGNC_id` INT NULL,
  `Description` LONGTEXT NULL,
  `Symbol` VARCHAR(45) NULL,
  `SwissProt_id` VARCHAR(10) NULL,
  PRIMARY KEY (`idGene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Role` (
  `Role` VARCHAR(45) NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`User` (
  `Username` VARCHAR(45) NOT NULL,
  `Bio` VARCHAR(45) NULL,
  `Role_idRole` INT NOT NULL,
  `Country_idCountry` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(100) NULL,
  PRIMARY KEY (`Username`),
  INDEX `fk_User_Role1_idx` (`Role_idRole` ASC) VISIBLE,
  INDEX `fk_User_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `RareGen`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `RareGen`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `Comment` LONGTEXT NULL,
  `User_Username` VARCHAR(45) NOT NULL,
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  `idResponse` INT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idComment`, `User_Username`, `Disease_idDiseases`),
  INDEX `fk_Comment_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  INDEX `fk_Comment_User1_idx` (`User_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `RareGen`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Login` (
  `Password` VARCHAR(60) NOT NULL,
  `User_Username` VARCHAR(45) NOT NULL,
  `Salt` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`User_Username`),
  INDEX `fk_User1` (`User_Username` ASC) VISIBLE,
  CONSTRAINT `fk_Login_User1`
    FOREIGN KEY (`User_Username`)
    REFERENCES `RareGen`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Gene_alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Gene_alias` (
  `Alias_name` VARCHAR(200) NOT NULL,
  `Gene_idGene` INT NOT NULL,
  PRIMARY KEY (`Gene_idGene`, `Alias_name`),
  INDEX `fk_Gene_alias_Gene1_idx` (`Gene_idGene` ASC) VISIBLE,
  CONSTRAINT `fk_Gene_alias_Gene1`
    FOREIGN KEY (`Gene_idGene`)
    REFERENCES `RareGen`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Prevalence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Prevalence` (
  `idPrevalence` INT NOT NULL,
  `Source` VARCHAR(200) NULL,
  `PrevalenceType` VARCHAR(200) NULL,
  `Prevalence` VARCHAR(200) NULL,
  `Geographic` VARCHAR(200) NULL,
  `ValMoy` VARCHAR(20) NULL,
  `ValidationStatus` VARCHAR(100) NULL,
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPrevalence`, `Disease_idDiseases`),
  INDEX `fk_Prevalence_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Prevalence_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease_alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease_alias` (
  `Alias_name` VARCHAR(300) NOT NULL,
  `Disease_Orphacode` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Alias_name`, `Disease_Orphacode`),
  INDEX `fk_Disease_alias_Disease1_idx` (`Disease_Orphacode` ASC) VISIBLE,
  CONSTRAINT `fk_Disease_alias_Disease1`
    FOREIGN KEY (`Disease_Orphacode`)
    REFERENCES `RareGen`.`Disease` (`Orphacode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Symptom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Symptom` (
  `Name` VARCHAR(300) NOT NULL,
  `Frequency` VARCHAR(300) NULL,
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Disease_idDiseases`, `Name`),
  INDEX `fk_Symptom_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Symptom_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Gene_has_Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Gene_has_Disease` (
  `Gene_idGene` INT NOT NULL,
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  `idMutation` INT NOT NULL,
  `Mutation_type` VARCHAR(100) NULL,
  `Mutation_name` VARCHAR(100) NULL,
  `Gene_position` VARCHAR(45) NULL,
  `Protein_position` VARCHAR(45) NULL,
  `Effect` VARCHAR(300) NULL,
  PRIMARY KEY (`Gene_idGene`, `Disease_idDiseases`, `idMutation`),
  INDEX `fk_Gene_has_Disease_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  INDEX `fk_Gene_has_Disease_Gene1_idx` (`Gene_idGene` ASC) VISIBLE,
  CONSTRAINT `fk_Gene_has_Disease_Gene1`
    FOREIGN KEY (`Gene_idGene`)
    REFERENCES `RareGen`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gene_has_Disease_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
