-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 15:15:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema RareGen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema RareGen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `RareGen` DEFAULT CHARACTER SET utf8 ;
USE `RareGen` ;

-- -----------------------------------------------------
-- Table `RareGen`.`Patient_Association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Patient_Association` (
  `idPatient_Associations` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NULL,
  `Country name` VARCHAR(45) NULL,
  `Contact_telephone` INT UNSIGNED NULL,
  `Contact email` VARCHAR(45) NULL,
  `Description` LONGTEXT NULL,
  PRIMARY KEY (`idPatient_Associations`),
  UNIQUE INDEX `idPatient_Associations_UNIQUE` (`idPatient_Associations` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease` (
  `idDiseases` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(500) NULL,
  `Orphacode` INT NULL,
  `Description` LONGTEXT NULL,
  `Treatments` LONGTEXT NULL,
  `Symptoms` LONGTEXT NULL,
  PRIMARY KEY (`idDiseases`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease_has_Patient_Association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease_has_Patient_Association` (
  `Diseases_idDiseases` INT UNSIGNED NOT NULL,
  `Patient Associations_idPatient_Associations` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Diseases_idDiseases`, `Patient Associations_idPatient_Associations`),
  INDEX `fk_Diseases_has_Patient Associations_Patient Associations1_idx` (`Patient Associations_idPatient_Associations` ASC) VISIBLE,
  INDEX `fk_Diseases_has_Patient Associations_Diseases_idx` (`Diseases_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Diseases_has_Patient Associations_Diseases`
    FOREIGN KEY (`Diseases_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diseases_has_Patient Associations_Patient Associations1`
    FOREIGN KEY (`Patient Associations_idPatient_Associations`)
    REFERENCES `RareGen`.`Patient_Association` (`idPatient_Associations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Country` (
  `idCountry` INT NOT NULL,
  `Country name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCountry`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Country_has_Patient_Association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Country_has_Patient_Association` (
  `Country_idCountry` INT NOT NULL,
  `Patient Association_idPatient_Associations` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Country_idCountry`, `Patient Association_idPatient_Associations`),
  INDEX `fk_Country_has_Patient Association_Patient Association1_idx` (`Patient Association_idPatient_Associations` ASC) VISIBLE,
  INDEX `fk_Country_has_Patient Association_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Country_has_Patient Association_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `RareGen`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Country_has_Patient Association_Patient Association1`
    FOREIGN KEY (`Patient Association_idPatient_Associations`)
    REFERENCES `RareGen`.`Patient_Association` (`idPatient_Associations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Gene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Gene` (
  `idGene` INT NOT NULL,
  `Name` VARCHAR(300) NULL,
  `Gene_type` VARCHAR(100) NULL,
  `Locus` VARCHAR(100) NULL,
  `Ensembl_id` VARCHAR(15) NULL,
  `OMIM_id` INT NULL,
  `GenAtlas_id` VARCHAR(20) NULL,
  `HGNC_id` INT NULL,
  `Description` LONGTEXT NULL,
  `Symbol` VARCHAR(45) NULL,
  `SwissProt_id` VARCHAR(10) NULL,
  PRIMARY KEY (`idGene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Mutation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Mutation_type` (
  `idMutation type` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idMutation type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Mutation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Mutation` (
  `idMutation` VARCHAR(15) NOT NULL,
  `Description` LONGTEXT NULL,
  `Mutation type_idMutation type` INT NULL,
  `Gene_idGene` INT NOT NULL,
  PRIMARY KEY (`idMutation`),
  INDEX `fk_Mutation_Mutation type1_idx` (`Mutation type_idMutation type` ASC) VISIBLE,
  INDEX `fk_Mutation_Gene1_idx` (`Gene_idGene` ASC) VISIBLE,
  CONSTRAINT `fk_Mutation_Mutation type1`
    FOREIGN KEY (`Mutation type_idMutation type`)
    REFERENCES `RareGen`.`Mutation_type` (`idMutation type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mutation_Gene1`
    FOREIGN KEY (`Gene_idGene`)
    REFERENCES `RareGen`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Role` (
  `Role` VARCHAR(45) NOT NULL,
  `idRole` INT NOT NULL,
  PRIMARY KEY (`idRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`User` (
  `idUser` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Bio` VARCHAR(45) NULL,
  `Role_idRole` INT NOT NULL,
  `Country_idCountry` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Role1_idx` (`Role_idRole` ASC) VISIBLE,
  INDEX `fk_User_Country1_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_idRole`)
    REFERENCES `RareGen`.`Role` (`idRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `RareGen`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Comment` (
  `idComment` INT NOT NULL,
  `Comment` LONGTEXT NULL,
  `User_idUser` INT NOT NULL,
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  `idResponse` INT NULL,
  `Date` DATE NULL,
  PRIMARY KEY (`idComment`, `User_idUser`, `Disease_idDiseases`),
  INDEX `fk_Comment_User1_idx` (`User_idUser` ASC) VISIBLE,
  INDEX `fk_Comment_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Comment_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `RareGen`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comment_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Login` (
  `Password` VARCHAR(45) NOT NULL,
  `idUser` INT NOT NULL,
  INDEX `fk_Login_User1_idx` (`idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Login_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `RareGen`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Publisher` (
  `idPublisher` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idPublisher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Journal` (
  `idJournal` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Publisher_idPublisher` INT NOT NULL,
  PRIMARY KEY (`idJournal`, `Publisher_idPublisher`),
  INDEX `fk_Journal_Publisher1_idx` (`Publisher_idPublisher` ASC) VISIBLE,
  CONSTRAINT `fk_Journal_Publisher1`
    FOREIGN KEY (`Publisher_idPublisher`)
    REFERENCES `RareGen`.`Publisher` (`idPublisher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Paper` (
  `idPaper` INT NOT NULL,
  `Title` LONGTEXT NULL,
  `Year` INT NULL,
  `Journal_idJournal` INT NOT NULL,
  PRIMARY KEY (`idPaper`, `Journal_idJournal`),
  INDEX `fk_Paper_Journal1_idx` (`Journal_idJournal` ASC) VISIBLE,
  CONSTRAINT `fk_Paper_Journal1`
    FOREIGN KEY (`Journal_idJournal`)
    REFERENCES `RareGen`.`Journal` (`idJournal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Author` (
  `idAuthor` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Surname` VARCHAR(100) NULL,
  PRIMARY KEY (`idAuthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease_has_Paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease_has_Paper` (
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  `Paper_idPaper` INT NOT NULL,
  PRIMARY KEY (`Disease_idDiseases`, `Paper_idPaper`),
  INDEX `fk_Disease_has_Paper_Paper1_idx` (`Paper_idPaper` ASC) VISIBLE,
  INDEX `fk_Disease_has_Paper_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Disease_has_Paper_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disease_has_Paper_Paper1`
    FOREIGN KEY (`Paper_idPaper`)
    REFERENCES `RareGen`.`Paper` (`idPaper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Paper_has_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Paper_has_Author` (
  `Paper_idPaper` INT NOT NULL,
  `Author_idAuthor` INT NOT NULL,
  PRIMARY KEY (`Paper_idPaper`, `Author_idAuthor`),
  INDEX `fk_Paper_has_Author_Author1_idx` (`Author_idAuthor` ASC) VISIBLE,
  INDEX `fk_Paper_has_Author_Paper1_idx` (`Paper_idPaper` ASC) VISIBLE,
  CONSTRAINT `fk_Paper_has_Author_Paper1`
    FOREIGN KEY (`Paper_idPaper`)
    REFERENCES `RareGen`.`Paper` (`idPaper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paper_has_Author_Author1`
    FOREIGN KEY (`Author_idAuthor`)
    REFERENCES `RareGen`.`Author` (`idAuthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Gene_alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Gene_alias` (
  `Alias_name` VARCHAR(200) NOT NULL,
  `Gene_idGene` INT NOT NULL,
  PRIMARY KEY (`Gene_idGene`, `Alias_name`),
  INDEX `fk_Gene_alias_Gene1_idx` (`Gene_idGene` ASC) VISIBLE,
  CONSTRAINT `fk_Gene_alias_Gene1`
    FOREIGN KEY (`Gene_idGene`)
    REFERENCES `RareGen`.`Gene` (`idGene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Disease_has_Mutation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Disease_has_Mutation` (
  `Disease_idDiseases` INT UNSIGNED NOT NULL,
  `Mutation_idMutation` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Disease_idDiseases`, `Mutation_idMutation`),
  INDEX `fk_Disease_has_Mutation_Mutation1_idx` (`Mutation_idMutation` ASC) VISIBLE,
  INDEX `fk_Disease_has_Mutation_Disease1_idx` (`Disease_idDiseases` ASC) VISIBLE,
  CONSTRAINT `fk_Disease_has_Mutation_Disease1`
    FOREIGN KEY (`Disease_idDiseases`)
    REFERENCES `RareGen`.`Disease` (`idDiseases`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Disease_has_Mutation_Mutation1`
    FOREIGN KEY (`Mutation_idMutation`)
    REFERENCES `RareGen`.`Mutation` (`idMutation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RareGen`.`Mutation_has_Paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RareGen`.`Mutation_has_Paper` (
  `Mutation_idMutation` VARCHAR(15) NOT NULL,
  `Paper_idPaper` INT NOT NULL,
  PRIMARY KEY (`Mutation_idMutation`, `Paper_idPaper`),
  INDEX `fk_Mutation_has_Paper_Paper1_idx` (`Paper_idPaper` ASC) VISIBLE,
  INDEX `fk_Mutation_has_Paper_Mutation1_idx` (`Mutation_idMutation` ASC) VISIBLE,
  CONSTRAINT `fk_Mutation_has_Paper_Mutation1`
    FOREIGN KEY (`Mutation_idMutation`)
    REFERENCES `RareGen`.`Mutation` (`idMutation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mutation_has_Paper_Paper1`
    FOREIGN KEY (`Paper_idPaper`)
    REFERENCES `RareGen`.`Paper` (`idPaper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
